// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gold5g.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoundInfo struct {
	// 游戏轮次
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本轮游戏开始时间
	BeginTime int64 `protobuf:"varint,2,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	// 本轮游戏结束时间
	EndTime int64 `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	// 最新的买票时间
	LastTicketTime int64 `protobuf:"varint,5,opt,name=lastTicketTime,proto3" json:"lastTicketTime,omitempty"`
	// 预留字段，最新的ticket的价格
	LastTicketPrice float64 `protobuf:"fixed64,6,opt,name=lastTicketPrice,proto3" json:"lastTicketPrice,omitempty"`
	// 当前公排池里奖金
	BonusSortPool float64 `protobuf:"fixed64,7,opt,name=bonusSortPool,proto3" json:"bonusSortPool,omitempty"`
	// 公排池排队用户信息
	SortPoolInfo []*InTicketInfo `protobuf:"bytes,8,rep,name=sortPoolInfo,proto3" json:"sortPoolInfo,omitempty"`
	// 本轮游戏奖金池总额
	BonusPool float64 `protobuf:"fixed64,9,opt,name=bonusPool,proto3" json:"bonusPool,omitempty"`
	// 本轮游戏参与地址数
	UserCount int64 `protobuf:"varint,10,opt,name=userCount,proto3" json:"userCount,omitempty"`
	// 本轮游戏募集到的ticket票数
	TicketCount int64 `protobuf:"varint,11,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	// 距离开奖剩余时间
	RemainTime int64 `protobuf:"varint,12,opt,name=remainTime,proto3" json:"remainTime,omitempty"`
	// 最近一次更新时间
	UpdateTime           int64    `protobuf:"varint,13,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundInfo) Reset()         { *m = RoundInfo{} }
func (m *RoundInfo) String() string { return proto.CompactTextString(m) }
func (*RoundInfo) ProtoMessage()    {}
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{0}
}
func (m *RoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfo.Unmarshal(m, b)
}
func (m *RoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfo.Marshal(b, m, deterministic)
}
func (dst *RoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfo.Merge(dst, src)
}
func (m *RoundInfo) XXX_Size() int {
	return xxx_messageInfo_RoundInfo.Size(m)
}
func (m *RoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfo proto.InternalMessageInfo

func (m *RoundInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *RoundInfo) GetBeginTime() int64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *RoundInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoundInfo) GetLastTicketTime() int64 {
	if m != nil {
		return m.LastTicketTime
	}
	return 0
}

func (m *RoundInfo) GetLastTicketPrice() float64 {
	if m != nil {
		return m.LastTicketPrice
	}
	return 0
}

func (m *RoundInfo) GetBonusSortPool() float64 {
	if m != nil {
		return m.BonusSortPool
	}
	return 0
}

func (m *RoundInfo) GetSortPoolInfo() []*InTicketInfo {
	if m != nil {
		return m.SortPoolInfo
	}
	return nil
}

func (m *RoundInfo) GetBonusPool() float64 {
	if m != nil {
		return m.BonusPool
	}
	return 0
}

func (m *RoundInfo) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *RoundInfo) GetTicketCount() int64 {
	if m != nil {
		return m.TicketCount
	}
	return 0
}

func (m *RoundInfo) GetRemainTime() int64 {
	if m != nil {
		return m.RemainTime
	}
	return 0
}

func (m *RoundInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type RoundsInfo struct {
	RoundsInfo           []*RoundInfo `protobuf:"bytes,1,rep,name=roundsInfo,proto3" json:"roundsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoundsInfo) Reset()         { *m = RoundsInfo{} }
func (m *RoundsInfo) String() string { return proto.CompactTextString(m) }
func (*RoundsInfo) ProtoMessage()    {}
func (*RoundsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{1}
}
func (m *RoundsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundsInfo.Unmarshal(m, b)
}
func (m *RoundsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundsInfo.Marshal(b, m, deterministic)
}
func (dst *RoundsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundsInfo.Merge(dst, src)
}
func (m *RoundsInfo) XXX_Size() int {
	return xxx_messageInfo_RoundsInfo.Size(m)
}
func (m *RoundsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundsInfo proto.InternalMessageInfo

func (m *RoundsInfo) GetRoundsInfo() []*RoundInfo {
	if m != nil {
		return m.RoundsInfo
	}
	return nil
}

type TicketInfo struct {
	// 游戏轮次  (是由系统合约填写后存储）
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本次购买ticket的价格 (是由系统合约填写后存储）
	TicketPrice float64 `protobuf:"fixed64,2,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	// 用户本次买的ticket的数量
	TicketNum int64 `protobuf:"varint,3,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	// 用户地址 (是由系统合约填写后存储）
	Addr string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// 交易确认存储时间（被打包的时间）
	BuyTicketTime int64 `protobuf:"varint,5,opt,name=buyTicketTime,proto3" json:"buyTicketTime,omitempty"`
	// 买票的txHash
	BuyTicketTxHash string `protobuf:"bytes,6,opt,name=buyTicketTxHash,proto3" json:"buyTicketTxHash,omitempty"`
	// index
	Index                int64    `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketInfo) Reset()         { *m = TicketInfo{} }
func (m *TicketInfo) String() string { return proto.CompactTextString(m) }
func (*TicketInfo) ProtoMessage()    {}
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{2}
}
func (m *TicketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketInfo.Unmarshal(m, b)
}
func (m *TicketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketInfo.Marshal(b, m, deterministic)
}
func (dst *TicketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketInfo.Merge(dst, src)
}
func (m *TicketInfo) XXX_Size() int {
	return xxx_messageInfo_TicketInfo.Size(m)
}
func (m *TicketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TicketInfo proto.InternalMessageInfo

func (m *TicketInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *TicketInfo) GetTicketPrice() float64 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

func (m *TicketInfo) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

func (m *TicketInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *TicketInfo) GetBuyTicketTime() int64 {
	if m != nil {
		return m.BuyTicketTime
	}
	return 0
}

func (m *TicketInfo) GetBuyTicketTxHash() string {
	if m != nil {
		return m.BuyTicketTxHash
	}
	return ""
}

func (m *TicketInfo) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type InTicketInfo struct {
	// 用户本次买的ticket的数量
	TicketNum int64 `protobuf:"varint,3,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	// 用户地址 (是由系统合约填写后存储）
	Addr string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// 交易确认存储时间（被打包的时间）
	BuyTicketTime        int64    `protobuf:"varint,5,opt,name=buyTicketTime,proto3" json:"buyTicketTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InTicketInfo) Reset()         { *m = InTicketInfo{} }
func (m *InTicketInfo) String() string { return proto.CompactTextString(m) }
func (*InTicketInfo) ProtoMessage()    {}
func (*InTicketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{3}
}
func (m *InTicketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InTicketInfo.Unmarshal(m, b)
}
func (m *InTicketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InTicketInfo.Marshal(b, m, deterministic)
}
func (dst *InTicketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InTicketInfo.Merge(dst, src)
}
func (m *InTicketInfo) XXX_Size() int {
	return xxx_messageInfo_InTicketInfo.Size(m)
}
func (m *InTicketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InTicketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InTicketInfo proto.InternalMessageInfo

func (m *InTicketInfo) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

func (m *InTicketInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *InTicketInfo) GetBuyTicketTime() int64 {
	if m != nil {
		return m.BuyTicketTime
	}
	return 0
}

type OutTicketInfo struct {
	// 用户本次买的ticket的数量
	TicketNum int64 `protobuf:"varint,3,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	// 用户地址 (是由系统合约填写后存储）
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutTicketInfo) Reset()         { *m = OutTicketInfo{} }
func (m *OutTicketInfo) String() string { return proto.CompactTextString(m) }
func (*OutTicketInfo) ProtoMessage()    {}
func (*OutTicketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{4}
}
func (m *OutTicketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutTicketInfo.Unmarshal(m, b)
}
func (m *OutTicketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutTicketInfo.Marshal(b, m, deterministic)
}
func (dst *OutTicketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutTicketInfo.Merge(dst, src)
}
func (m *OutTicketInfo) XXX_Size() int {
	return xxx_messageInfo_OutTicketInfo.Size(m)
}
func (m *OutTicketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutTicketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutTicketInfo proto.InternalMessageInfo

func (m *OutTicketInfo) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

func (m *OutTicketInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// message for execs.gold5g
type Gold5GAction struct {
	// Types that are valid to be assigned to Value:
	//	*Gold5GAction_Start
	//	*Gold5GAction_Draw
	//	*Gold5GAction_Buy
	Value                isGold5GAction_Value `protobuf_oneof:"value"`
	Ty                   int32                `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Gold5GAction) Reset()         { *m = Gold5GAction{} }
func (m *Gold5GAction) String() string { return proto.CompactTextString(m) }
func (*Gold5GAction) ProtoMessage()    {}
func (*Gold5GAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{5}
}
func (m *Gold5GAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GAction.Unmarshal(m, b)
}
func (m *Gold5GAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GAction.Marshal(b, m, deterministic)
}
func (dst *Gold5GAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GAction.Merge(dst, src)
}
func (m *Gold5GAction) XXX_Size() int {
	return xxx_messageInfo_Gold5GAction.Size(m)
}
func (m *Gold5GAction) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GAction.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GAction proto.InternalMessageInfo

type isGold5GAction_Value interface {
	isGold5GAction_Value()
}

type Gold5GAction_Start struct {
	Start *Gold5GStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}
type Gold5GAction_Draw struct {
	Draw *Gold5GLuckyDraw `protobuf:"bytes,2,opt,name=draw,proto3,oneof"`
}
type Gold5GAction_Buy struct {
	Buy *Gold5GBuyTicket `protobuf:"bytes,3,opt,name=buy,proto3,oneof"`
}

func (*Gold5GAction_Start) isGold5GAction_Value() {}
func (*Gold5GAction_Draw) isGold5GAction_Value()  {}
func (*Gold5GAction_Buy) isGold5GAction_Value()   {}

func (m *Gold5GAction) GetValue() isGold5GAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Gold5GAction) GetStart() *Gold5GStart {
	if x, ok := m.GetValue().(*Gold5GAction_Start); ok {
		return x.Start
	}
	return nil
}

func (m *Gold5GAction) GetDraw() *Gold5GLuckyDraw {
	if x, ok := m.GetValue().(*Gold5GAction_Draw); ok {
		return x.Draw
	}
	return nil
}

func (m *Gold5GAction) GetBuy() *Gold5GBuyTicket {
	if x, ok := m.GetValue().(*Gold5GAction_Buy); ok {
		return x.Buy
	}
	return nil
}

func (m *Gold5GAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Gold5GAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Gold5GAction_OneofMarshaler, _Gold5GAction_OneofUnmarshaler, _Gold5GAction_OneofSizer, []interface{}{
		(*Gold5GAction_Start)(nil),
		(*Gold5GAction_Draw)(nil),
		(*Gold5GAction_Buy)(nil),
	}
}

func _Gold5GAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Gold5GAction)
	// value
	switch x := m.Value.(type) {
	case *Gold5GAction_Start:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Start); err != nil {
			return err
		}
	case *Gold5GAction_Draw:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Draw); err != nil {
			return err
		}
	case *Gold5GAction_Buy:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Buy); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Gold5GAction.Value has unexpected type %T", x)
	}
	return nil
}

func _Gold5GAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Gold5GAction)
	switch tag {
	case 1: // value.start
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gold5GStart)
		err := b.DecodeMessage(msg)
		m.Value = &Gold5GAction_Start{msg}
		return true, err
	case 2: // value.draw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gold5GLuckyDraw)
		err := b.DecodeMessage(msg)
		m.Value = &Gold5GAction_Draw{msg}
		return true, err
	case 3: // value.buy
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gold5GBuyTicket)
		err := b.DecodeMessage(msg)
		m.Value = &Gold5GAction_Buy{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Gold5GAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Gold5GAction)
	// value
	switch x := m.Value.(type) {
	case *Gold5GAction_Start:
		s := proto.Size(x.Start)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Gold5GAction_Draw:
		s := proto.Size(x.Draw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Gold5GAction_Buy:
		s := proto.Size(x.Buy)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Gold5GStart struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GStart) Reset()         { *m = Gold5GStart{} }
func (m *Gold5GStart) String() string { return proto.CompactTextString(m) }
func (*Gold5GStart) ProtoMessage()    {}
func (*Gold5GStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{6}
}
func (m *Gold5GStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GStart.Unmarshal(m, b)
}
func (m *Gold5GStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GStart.Marshal(b, m, deterministic)
}
func (dst *Gold5GStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GStart.Merge(dst, src)
}
func (m *Gold5GStart) XXX_Size() int {
	return xxx_messageInfo_Gold5GStart.Size(m)
}
func (m *Gold5GStart) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GStart.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GStart proto.InternalMessageInfo

func (m *Gold5GStart) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Gold5GLuckyDraw struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GLuckyDraw) Reset()         { *m = Gold5GLuckyDraw{} }
func (m *Gold5GLuckyDraw) String() string { return proto.CompactTextString(m) }
func (*Gold5GLuckyDraw) ProtoMessage()    {}
func (*Gold5GLuckyDraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{7}
}
func (m *Gold5GLuckyDraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GLuckyDraw.Unmarshal(m, b)
}
func (m *Gold5GLuckyDraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GLuckyDraw.Marshal(b, m, deterministic)
}
func (dst *Gold5GLuckyDraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GLuckyDraw.Merge(dst, src)
}
func (m *Gold5GLuckyDraw) XXX_Size() int {
	return xxx_messageInfo_Gold5GLuckyDraw.Size(m)
}
func (m *Gold5GLuckyDraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GLuckyDraw.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GLuckyDraw proto.InternalMessageInfo

func (m *Gold5GLuckyDraw) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Gold5GBuyTicket struct {
	// 用户本次买的key的数量
	TicketNum            int64    `protobuf:"varint,3,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GBuyTicket) Reset()         { *m = Gold5GBuyTicket{} }
func (m *Gold5GBuyTicket) String() string { return proto.CompactTextString(m) }
func (*Gold5GBuyTicket) ProtoMessage()    {}
func (*Gold5GBuyTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{8}
}
func (m *Gold5GBuyTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GBuyTicket.Unmarshal(m, b)
}
func (m *Gold5GBuyTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GBuyTicket.Marshal(b, m, deterministic)
}
func (dst *Gold5GBuyTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GBuyTicket.Merge(dst, src)
}
func (m *Gold5GBuyTicket) XXX_Size() int {
	return xxx_messageInfo_Gold5GBuyTicket.Size(m)
}
func (m *Gold5GBuyTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GBuyTicket.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GBuyTicket proto.InternalMessageInfo

func (m *Gold5GBuyTicket) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

// 查询Gold5G游戏信息
type QueryGold5GByRound struct {
	// 轮次，默认查询最新的
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGold5GByRound) Reset()         { *m = QueryGold5GByRound{} }
func (m *QueryGold5GByRound) String() string { return proto.CompactTextString(m) }
func (*QueryGold5GByRound) ProtoMessage()    {}
func (*QueryGold5GByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{9}
}
func (m *QueryGold5GByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGold5GByRound.Unmarshal(m, b)
}
func (m *QueryGold5GByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGold5GByRound.Marshal(b, m, deterministic)
}
func (dst *QueryGold5GByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGold5GByRound.Merge(dst, src)
}
func (m *QueryGold5GByRound) XXX_Size() int {
	return xxx_messageInfo_QueryGold5GByRound.Size(m)
}
func (m *QueryGold5GByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGold5GByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGold5GByRound proto.InternalMessageInfo

func (m *QueryGold5GByRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type QueryGold5GLastRound struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGold5GLastRound) Reset()         { *m = QueryGold5GLastRound{} }
func (m *QueryGold5GLastRound) String() string { return proto.CompactTextString(m) }
func (*QueryGold5GLastRound) ProtoMessage()    {}
func (*QueryGold5GLastRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{10}
}
func (m *QueryGold5GLastRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGold5GLastRound.Unmarshal(m, b)
}
func (m *QueryGold5GLastRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGold5GLastRound.Marshal(b, m, deterministic)
}
func (dst *QueryGold5GLastRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGold5GLastRound.Merge(dst, src)
}
func (m *QueryGold5GLastRound) XXX_Size() int {
	return xxx_messageInfo_QueryGold5GLastRound.Size(m)
}
func (m *QueryGold5GLastRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGold5GLastRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGold5GLastRound proto.InternalMessageInfo

type QueryGold5GListByRound struct {
	// 轮次，默认查询最新的
	StartRound int64 `protobuf:"varint,1,opt,name=startRound,proto3" json:"startRound,omitempty"`
	// 单页返回多少条记录，默认返回10条，单次最多返回50条
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGold5GListByRound) Reset()         { *m = QueryGold5GListByRound{} }
func (m *QueryGold5GListByRound) String() string { return proto.CompactTextString(m) }
func (*QueryGold5GListByRound) ProtoMessage()    {}
func (*QueryGold5GListByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{11}
}
func (m *QueryGold5GListByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGold5GListByRound.Unmarshal(m, b)
}
func (m *QueryGold5GListByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGold5GListByRound.Marshal(b, m, deterministic)
}
func (dst *QueryGold5GListByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGold5GListByRound.Merge(dst, src)
}
func (m *QueryGold5GListByRound) XXX_Size() int {
	return xxx_messageInfo_QueryGold5GListByRound.Size(m)
}
func (m *QueryGold5GListByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGold5GListByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGold5GListByRound proto.InternalMessageInfo

func (m *QueryGold5GListByRound) GetStartRound() int64 {
	if m != nil {
		return m.StartRound
	}
	return 0
}

func (m *QueryGold5GListByRound) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryGold5GListByRound) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// key 信息查询
type QueryBuyRecordByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBuyRecordByRoundAndAddr) Reset()         { *m = QueryBuyRecordByRoundAndAddr{} }
func (m *QueryBuyRecordByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryBuyRecordByRoundAndAddr) ProtoMessage()    {}
func (*QueryBuyRecordByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{12}
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryBuyRecordByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Merge(dst, src)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Size(m)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBuyRecordByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBuyRecordByRoundAndAddr proto.InternalMessageInfo

func (m *QueryBuyRecordByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryBuyRecordByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *QueryBuyRecordByRoundAndAddr) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 用户key数量查询
type QueryTicketInfoByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTicketInfoByRoundAndAddr) Reset()         { *m = QueryTicketInfoByRoundAndAddr{} }
func (m *QueryTicketInfoByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryTicketInfoByRoundAndAddr) ProtoMessage()    {}
func (*QueryTicketInfoByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{13}
}
func (m *QueryTicketInfoByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketInfoByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryTicketInfoByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketInfoByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryTicketInfoByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketInfoByRoundAndAddr.Merge(dst, src)
}
func (m *QueryTicketInfoByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryTicketInfoByRoundAndAddr.Size(m)
}
func (m *QueryTicketInfoByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketInfoByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketInfoByRoundAndAddr proto.InternalMessageInfo

func (m *QueryTicketInfoByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryTicketInfoByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type QueryAddrInfo struct {
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Direction            int32    `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAddrInfo) Reset()         { *m = QueryAddrInfo{} }
func (m *QueryAddrInfo) String() string { return proto.CompactTextString(m) }
func (*QueryAddrInfo) ProtoMessage()    {}
func (*QueryAddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{14}
}
func (m *QueryAddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAddrInfo.Unmarshal(m, b)
}
func (m *QueryAddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAddrInfo.Marshal(b, m, deterministic)
}
func (dst *QueryAddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddrInfo.Merge(dst, src)
}
func (m *QueryAddrInfo) XXX_Size() int {
	return xxx_messageInfo_QueryAddrInfo.Size(m)
}
func (m *QueryAddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddrInfo proto.InternalMessageInfo

func (m *QueryAddrInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryAddrInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *QueryAddrInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryAddrInfo) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type Gold5GRecord struct {
	// 用户地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// index
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// round
	Round                int64    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GRecord) Reset()         { *m = Gold5GRecord{} }
func (m *Gold5GRecord) String() string { return proto.CompactTextString(m) }
func (*Gold5GRecord) ProtoMessage()    {}
func (*Gold5GRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{15}
}
func (m *Gold5GRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GRecord.Unmarshal(m, b)
}
func (m *Gold5GRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GRecord.Marshal(b, m, deterministic)
}
func (dst *Gold5GRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GRecord.Merge(dst, src)
}
func (m *Gold5GRecord) XXX_Size() int {
	return xxx_messageInfo_Gold5GRecord.Size(m)
}
func (m *Gold5GRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GRecord.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GRecord proto.InternalMessageInfo

func (m *Gold5GRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Gold5GRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Gold5GRecord) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Gold5GStartRound struct {
	// round
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GStartRound) Reset()         { *m = Gold5GStartRound{} }
func (m *Gold5GStartRound) String() string { return proto.CompactTextString(m) }
func (*Gold5GStartRound) ProtoMessage()    {}
func (*Gold5GStartRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{16}
}
func (m *Gold5GStartRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GStartRound.Unmarshal(m, b)
}
func (m *Gold5GStartRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GStartRound.Marshal(b, m, deterministic)
}
func (dst *Gold5GStartRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GStartRound.Merge(dst, src)
}
func (m *Gold5GStartRound) XXX_Size() int {
	return xxx_messageInfo_Gold5GStartRound.Size(m)
}
func (m *Gold5GStartRound) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GStartRound.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GStartRound proto.InternalMessageInfo

func (m *Gold5GStartRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Gold5GDrawRound struct {
	// round
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GDrawRound) Reset()         { *m = Gold5GDrawRound{} }
func (m *Gold5GDrawRound) String() string { return proto.CompactTextString(m) }
func (*Gold5GDrawRound) ProtoMessage()    {}
func (*Gold5GDrawRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{17}
}
func (m *Gold5GDrawRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GDrawRound.Unmarshal(m, b)
}
func (m *Gold5GDrawRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GDrawRound.Marshal(b, m, deterministic)
}
func (dst *Gold5GDrawRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GDrawRound.Merge(dst, src)
}
func (m *Gold5GDrawRound) XXX_Size() int {
	return xxx_messageInfo_Gold5GDrawRound.Size(m)
}
func (m *Gold5GDrawRound) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GDrawRound.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GDrawRound proto.InternalMessageInfo

func (m *Gold5GDrawRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type Gold5GBuyRecord struct {
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gold5GBuyRecord) Reset()         { *m = Gold5GBuyRecord{} }
func (m *Gold5GBuyRecord) String() string { return proto.CompactTextString(m) }
func (*Gold5GBuyRecord) ProtoMessage()    {}
func (*Gold5GBuyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{18}
}
func (m *Gold5GBuyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gold5GBuyRecord.Unmarshal(m, b)
}
func (m *Gold5GBuyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gold5GBuyRecord.Marshal(b, m, deterministic)
}
func (dst *Gold5GBuyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gold5GBuyRecord.Merge(dst, src)
}
func (m *Gold5GBuyRecord) XXX_Size() int {
	return xxx_messageInfo_Gold5GBuyRecord.Size(m)
}
func (m *Gold5GBuyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_Gold5GBuyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_Gold5GBuyRecord proto.InternalMessageInfo

func (m *Gold5GBuyRecord) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Gold5GBuyRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Gold5GBuyRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// Gold5G round查询返回数据
type ReplyGold5GList struct {
	Rounds               []*RoundInfo `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyGold5GList) Reset()         { *m = ReplyGold5GList{} }
func (m *ReplyGold5GList) String() string { return proto.CompactTextString(m) }
func (*ReplyGold5GList) ProtoMessage()    {}
func (*ReplyGold5GList) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{19}
}
func (m *ReplyGold5GList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGold5GList.Unmarshal(m, b)
}
func (m *ReplyGold5GList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGold5GList.Marshal(b, m, deterministic)
}
func (dst *ReplyGold5GList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGold5GList.Merge(dst, src)
}
func (m *ReplyGold5GList) XXX_Size() int {
	return xxx_messageInfo_ReplyGold5GList.Size(m)
}
func (m *ReplyGold5GList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGold5GList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGold5GList proto.InternalMessageInfo

func (m *ReplyGold5GList) GetRounds() []*RoundInfo {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type ReplyGold5G struct {
	Round                *RoundInfo `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyGold5G) Reset()         { *m = ReplyGold5G{} }
func (m *ReplyGold5G) String() string { return proto.CompactTextString(m) }
func (*ReplyGold5G) ProtoMessage()    {}
func (*ReplyGold5G) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{20}
}
func (m *ReplyGold5G) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyGold5G.Unmarshal(m, b)
}
func (m *ReplyGold5G) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyGold5G.Marshal(b, m, deterministic)
}
func (dst *ReplyGold5G) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyGold5G.Merge(dst, src)
}
func (m *ReplyGold5G) XXX_Size() int {
	return xxx_messageInfo_ReplyGold5G.Size(m)
}
func (m *ReplyGold5G) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyGold5G.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyGold5G proto.InternalMessageInfo

func (m *ReplyGold5G) GetRound() *RoundInfo {
	if m != nil {
		return m.Round
	}
	return nil
}

// 用户查询买的key信息返回数据
type ReplyBuyRecord struct {
	RecordList           []*TicketInfo `protobuf:"bytes,1,rep,name=recordList,proto3" json:"recordList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyBuyRecord) Reset()         { *m = ReplyBuyRecord{} }
func (m *ReplyBuyRecord) String() string { return proto.CompactTextString(m) }
func (*ReplyBuyRecord) ProtoMessage()    {}
func (*ReplyBuyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{21}
}
func (m *ReplyBuyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBuyRecord.Unmarshal(m, b)
}
func (m *ReplyBuyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBuyRecord.Marshal(b, m, deterministic)
}
func (dst *ReplyBuyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBuyRecord.Merge(dst, src)
}
func (m *ReplyBuyRecord) XXX_Size() int {
	return xxx_messageInfo_ReplyBuyRecord.Size(m)
}
func (m *ReplyBuyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBuyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBuyRecord proto.InternalMessageInfo

func (m *ReplyBuyRecord) GetRecordList() []*TicketInfo {
	if m != nil {
		return m.RecordList
	}
	return nil
}

type ReplyKey struct {
	Ticket               *TicketInfo `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplyKey) Reset()         { *m = ReplyKey{} }
func (m *ReplyKey) String() string { return proto.CompactTextString(m) }
func (*ReplyKey) ProtoMessage()    {}
func (*ReplyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{22}
}
func (m *ReplyKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKey.Unmarshal(m, b)
}
func (m *ReplyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKey.Marshal(b, m, deterministic)
}
func (dst *ReplyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKey.Merge(dst, src)
}
func (m *ReplyKey) XXX_Size() int {
	return xxx_messageInfo_ReplyKey.Size(m)
}
func (m *ReplyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKey proto.InternalMessageInfo

func (m *ReplyKey) GetTicket() *TicketInfo {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type ReplyTicketCount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyTicketCount) Reset()         { *m = ReplyTicketCount{} }
func (m *ReplyTicketCount) String() string { return proto.CompactTextString(m) }
func (*ReplyTicketCount) ProtoMessage()    {}
func (*ReplyTicketCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{23}
}
func (m *ReplyTicketCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTicketCount.Unmarshal(m, b)
}
func (m *ReplyTicketCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTicketCount.Marshal(b, m, deterministic)
}
func (dst *ReplyTicketCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTicketCount.Merge(dst, src)
}
func (m *ReplyTicketCount) XXX_Size() int {
	return xxx_messageInfo_ReplyTicketCount.Size(m)
}
func (m *ReplyTicketCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTicketCount.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTicketCount proto.InternalMessageInfo

func (m *ReplyTicketCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReplyAddrInfoList struct {
	AddrInfoList         []*AddrInfo `protobuf:"bytes,1,rep,name=addrInfoList,proto3" json:"addrInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplyAddrInfoList) Reset()         { *m = ReplyAddrInfoList{} }
func (m *ReplyAddrInfoList) String() string { return proto.CompactTextString(m) }
func (*ReplyAddrInfoList) ProtoMessage()    {}
func (*ReplyAddrInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{24}
}
func (m *ReplyAddrInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAddrInfoList.Unmarshal(m, b)
}
func (m *ReplyAddrInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAddrInfoList.Marshal(b, m, deterministic)
}
func (dst *ReplyAddrInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAddrInfoList.Merge(dst, src)
}
func (m *ReplyAddrInfoList) XXX_Size() int {
	return xxx_messageInfo_ReplyAddrInfoList.Size(m)
}
func (m *ReplyAddrInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAddrInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAddrInfoList proto.InternalMessageInfo

func (m *ReplyAddrInfoList) GetAddrInfoList() []*AddrInfo {
	if m != nil {
		return m.AddrInfoList
	}
	return nil
}

type AddrInfo struct {
	// 用户地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// 用户本轮游戏总共买的票数
	TicketNum int64 `protobuf:"varint,2,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	// 买了几次
	BuyCount int64 `protobuf:"varint,3,opt,name=buyCount,proto3" json:"buyCount,omitempty"`
	// 第几轮
	Round int64 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	// 总的花费
	TotalCost float64 `protobuf:"fixed64,5,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	// 基于公排池的收益
	SortPoolBonus        float64  `protobuf:"fixed64,6,opt,name=sortPoolBonus,proto3" json:"sortPoolBonus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrInfo) Reset()         { *m = AddrInfo{} }
func (m *AddrInfo) String() string { return proto.CompactTextString(m) }
func (*AddrInfo) ProtoMessage()    {}
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{25}
}
func (m *AddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrInfo.Unmarshal(m, b)
}
func (m *AddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrInfo.Marshal(b, m, deterministic)
}
func (dst *AddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrInfo.Merge(dst, src)
}
func (m *AddrInfo) XXX_Size() int {
	return xxx_messageInfo_AddrInfo.Size(m)
}
func (m *AddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddrInfo proto.InternalMessageInfo

func (m *AddrInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AddrInfo) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

func (m *AddrInfo) GetBuyCount() int64 {
	if m != nil {
		return m.BuyCount
	}
	return 0
}

func (m *AddrInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *AddrInfo) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *AddrInfo) GetSortPoolBonus() float64 {
	if m != nil {
		return m.SortPoolBonus
	}
	return 0
}

// 合约内部日志记录，待补全
type ReceiptGold5G struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Round                int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Action               int64    `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`
	BuyCount             int64    `protobuf:"varint,5,opt,name=buyCount,proto3" json:"buyCount,omitempty"`
	TicketNum            int64    `protobuf:"varint,6,opt,name=ticketNum,proto3" json:"ticketNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptGold5G) Reset()         { *m = ReceiptGold5G{} }
func (m *ReceiptGold5G) String() string { return proto.CompactTextString(m) }
func (*ReceiptGold5G) ProtoMessage()    {}
func (*ReceiptGold5G) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{26}
}
func (m *ReceiptGold5G) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptGold5G.Unmarshal(m, b)
}
func (m *ReceiptGold5G) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptGold5G.Marshal(b, m, deterministic)
}
func (dst *ReceiptGold5G) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptGold5G.Merge(dst, src)
}
func (m *ReceiptGold5G) XXX_Size() int {
	return xxx_messageInfo_ReceiptGold5G.Size(m)
}
func (m *ReceiptGold5G) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptGold5G.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptGold5G proto.InternalMessageInfo

func (m *ReceiptGold5G) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptGold5G) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ReceiptGold5G) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReceiptGold5G) GetAction() int64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ReceiptGold5G) GetBuyCount() int64 {
	if m != nil {
		return m.BuyCount
	}
	return 0
}

func (m *ReceiptGold5G) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

type Config struct {
	ManagerAddr          string   `protobuf:"bytes,1,opt,name=managerAddr,proto3" json:"managerAddr,omitempty"`
	DeveloperAddr        string   `protobuf:"bytes,2,opt,name=developerAddr,proto3" json:"developerAddr,omitempty"`
	PartnerAddr          string   `protobuf:"bytes,3,opt,name=partnerAddr,proto3" json:"partnerAddr,omitempty"`
	FirstPrizeAddr       string   `protobuf:"bytes,4,opt,name=firstPrizeAddr,proto3" json:"firstPrizeAddr,omitempty"`
	SecondaryPrizeAddr   string   `protobuf:"bytes,5,opt,name=secondaryPrizeAddr,proto3" json:"secondaryPrizeAddr,omitempty"`
	PromotionAddr        string   `protobuf:"bytes,6,opt,name=promotionAddr,proto3" json:"promotionAddr,omitempty"`
	SupportFundAddr      string   `protobuf:"bytes,7,opt,name=supportFundAddr,proto3" json:"supportFundAddr,omitempty"`
	FirstPrizePerc       float64  `protobuf:"fixed64,8,opt,name=firstPrizePerc,proto3" json:"firstPrizePerc,omitempty"`
	SecondaryPrizePerc   float64  `protobuf:"fixed64,9,opt,name=secondaryPrizePerc,proto3" json:"secondaryPrizePerc,omitempty"`
	PoolBonusPerc        float64  `protobuf:"fixed64,10,opt,name=poolBonusPerc,proto3" json:"poolBonusPerc,omitempty"`
	SupportFund          float64  `protobuf:"fixed64,11,opt,name=supportFund,proto3" json:"supportFund,omitempty"`
	Partner              float64  `protobuf:"fixed64,12,opt,name=partner,proto3" json:"partner,omitempty"`
	Developer            float64  `protobuf:"fixed64,13,opt,name=developer,proto3" json:"developer,omitempty"`
	BonusPool            float64  `protobuf:"fixed64,14,opt,name=bonusPool,proto3" json:"bonusPool,omitempty"`
	Promotion            float64  `protobuf:"fixed64,15,opt,name=promotion,proto3" json:"promotion,omitempty"`
	LifeTime             int64    `protobuf:"varint,16,opt,name=lifeTime,proto3" json:"lifeTime,omitempty"`
	TicketIncrTime       int64    `protobuf:"varint,17,opt,name=ticketIncrTime,proto3" json:"ticketIncrTime,omitempty"`
	TicketPrice          float64  `protobuf:"fixed64,18,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_gold5g_3080699e66960f3f, []int{27}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetManagerAddr() string {
	if m != nil {
		return m.ManagerAddr
	}
	return ""
}

func (m *Config) GetDeveloperAddr() string {
	if m != nil {
		return m.DeveloperAddr
	}
	return ""
}

func (m *Config) GetPartnerAddr() string {
	if m != nil {
		return m.PartnerAddr
	}
	return ""
}

func (m *Config) GetFirstPrizeAddr() string {
	if m != nil {
		return m.FirstPrizeAddr
	}
	return ""
}

func (m *Config) GetSecondaryPrizeAddr() string {
	if m != nil {
		return m.SecondaryPrizeAddr
	}
	return ""
}

func (m *Config) GetPromotionAddr() string {
	if m != nil {
		return m.PromotionAddr
	}
	return ""
}

func (m *Config) GetSupportFundAddr() string {
	if m != nil {
		return m.SupportFundAddr
	}
	return ""
}

func (m *Config) GetFirstPrizePerc() float64 {
	if m != nil {
		return m.FirstPrizePerc
	}
	return 0
}

func (m *Config) GetSecondaryPrizePerc() float64 {
	if m != nil {
		return m.SecondaryPrizePerc
	}
	return 0
}

func (m *Config) GetPoolBonusPerc() float64 {
	if m != nil {
		return m.PoolBonusPerc
	}
	return 0
}

func (m *Config) GetSupportFund() float64 {
	if m != nil {
		return m.SupportFund
	}
	return 0
}

func (m *Config) GetPartner() float64 {
	if m != nil {
		return m.Partner
	}
	return 0
}

func (m *Config) GetDeveloper() float64 {
	if m != nil {
		return m.Developer
	}
	return 0
}

func (m *Config) GetBonusPool() float64 {
	if m != nil {
		return m.BonusPool
	}
	return 0
}

func (m *Config) GetPromotion() float64 {
	if m != nil {
		return m.Promotion
	}
	return 0
}

func (m *Config) GetLifeTime() int64 {
	if m != nil {
		return m.LifeTime
	}
	return 0
}

func (m *Config) GetTicketIncrTime() int64 {
	if m != nil {
		return m.TicketIncrTime
	}
	return 0
}

func (m *Config) GetTicketPrice() float64 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*RoundInfo)(nil), "types.RoundInfo")
	proto.RegisterType((*RoundsInfo)(nil), "types.RoundsInfo")
	proto.RegisterType((*TicketInfo)(nil), "types.TicketInfo")
	proto.RegisterType((*InTicketInfo)(nil), "types.InTicketInfo")
	proto.RegisterType((*OutTicketInfo)(nil), "types.OutTicketInfo")
	proto.RegisterType((*Gold5GAction)(nil), "types.Gold5GAction")
	proto.RegisterType((*Gold5GStart)(nil), "types.Gold5GStart")
	proto.RegisterType((*Gold5GLuckyDraw)(nil), "types.Gold5GLuckyDraw")
	proto.RegisterType((*Gold5GBuyTicket)(nil), "types.Gold5GBuyTicket")
	proto.RegisterType((*QueryGold5GByRound)(nil), "types.QueryGold5GByRound")
	proto.RegisterType((*QueryGold5GLastRound)(nil), "types.QueryGold5GLastRound")
	proto.RegisterType((*QueryGold5GListByRound)(nil), "types.QueryGold5GListByRound")
	proto.RegisterType((*QueryBuyRecordByRoundAndAddr)(nil), "types.QueryBuyRecordByRoundAndAddr")
	proto.RegisterType((*QueryTicketInfoByRoundAndAddr)(nil), "types.QueryTicketInfoByRoundAndAddr")
	proto.RegisterType((*QueryAddrInfo)(nil), "types.QueryAddrInfo")
	proto.RegisterType((*Gold5GRecord)(nil), "types.Gold5GRecord")
	proto.RegisterType((*Gold5GStartRound)(nil), "types.Gold5GStartRound")
	proto.RegisterType((*Gold5GDrawRound)(nil), "types.Gold5GDrawRound")
	proto.RegisterType((*Gold5GBuyRecord)(nil), "types.Gold5GBuyRecord")
	proto.RegisterType((*ReplyGold5GList)(nil), "types.ReplyGold5GList")
	proto.RegisterType((*ReplyGold5G)(nil), "types.ReplyGold5G")
	proto.RegisterType((*ReplyBuyRecord)(nil), "types.ReplyBuyRecord")
	proto.RegisterType((*ReplyKey)(nil), "types.ReplyKey")
	proto.RegisterType((*ReplyTicketCount)(nil), "types.ReplyTicketCount")
	proto.RegisterType((*ReplyAddrInfoList)(nil), "types.ReplyAddrInfoList")
	proto.RegisterType((*AddrInfo)(nil), "types.AddrInfo")
	proto.RegisterType((*ReceiptGold5G)(nil), "types.ReceiptGold5G")
	proto.RegisterType((*Config)(nil), "types.Config")
}

func init() { proto.RegisterFile("gold5g.proto", fileDescriptor_gold5g_3080699e66960f3f) }

var fileDescriptor_gold5g_3080699e66960f3f = []byte{
	// 1095 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x8e, 0xd7, 0xf1, 0x26, 0x7b, 0x76, 0xf3, 0x37, 0x54, 0x91, 0x85, 0x4a, 0x15, 0x19, 0x54,
	0x96, 0x08, 0x05, 0x48, 0x15, 0x71, 0x81, 0x84, 0xb4, 0x09, 0xa2, 0x89, 0xa8, 0x4a, 0x3a, 0xcd,
	0x35, 0x92, 0xd7, 0x9e, 0x5d, 0xac, 0xee, 0x7a, 0xac, 0xf1, 0xb8, 0xad, 0x79, 0x0e, 0x5e, 0x80,
	0x3b, 0x6e, 0xb8, 0xe1, 0x79, 0x78, 0x18, 0x34, 0x67, 0xc6, 0xf6, 0xd8, 0xf1, 0xe6, 0x82, 0x8a,
	0xbb, 0x9d, 0xef, 0x7c, 0x73, 0xe6, 0xfc, 0x7c, 0x33, 0x3e, 0x0b, 0x93, 0x25, 0x5f, 0xc5, 0x17,
	0xcb, 0xb3, 0x4c, 0x70, 0xc9, 0x89, 0x27, 0xcb, 0x8c, 0xe5, 0xc1, 0x9f, 0x2e, 0x8c, 0x28, 0x2f,
	0xd2, 0xf8, 0x26, 0x5d, 0x70, 0xf2, 0x08, 0x3c, 0xa1, 0x16, 0xbe, 0x73, 0xe2, 0x4c, 0x5d, 0xaa,
	0x17, 0xe4, 0x31, 0x8c, 0xe6, 0x6c, 0x99, 0xa4, 0x77, 0xc9, 0x9a, 0xf9, 0x03, 0xb4, 0x34, 0x00,
	0xf1, 0x61, 0x87, 0xa5, 0x31, 0xda, 0x5c, 0xb4, 0x55, 0x4b, 0xf2, 0x14, 0xf6, 0x57, 0x61, 0x2e,
	0xef, 0x92, 0xe8, 0x0d, 0x93, 0x48, 0xf0, 0x90, 0xd0, 0x41, 0xc9, 0x14, 0x0e, 0x1a, 0xe4, 0x56,
	0x24, 0x11, 0xf3, 0x87, 0x27, 0xce, 0xd4, 0xa1, 0x5d, 0x98, 0x7c, 0x06, 0x7b, 0x73, 0x9e, 0x16,
	0xf9, 0x6b, 0x2e, 0xe4, 0x2d, 0xe7, 0x2b, 0x7f, 0x07, 0x79, 0x6d, 0x90, 0x7c, 0x0b, 0x93, 0xdc,
	0xfc, 0x56, 0x59, 0xf9, 0xbb, 0x27, 0xee, 0x74, 0x7c, 0xfe, 0xd1, 0x19, 0x66, 0x7c, 0x76, 0x93,
	0x6a, 0x8f, 0xca, 0x44, 0x5b, 0x44, 0x4c, 0x54, 0x79, 0x42, 0xd7, 0x23, 0x74, 0xdd, 0x00, 0xca,
	0x5a, 0xe4, 0x4c, 0x5c, 0xf1, 0x22, 0x95, 0x3e, 0xe8, 0x32, 0xd4, 0x00, 0x39, 0x81, 0xb1, 0x44,
	0xbf, 0xda, 0x3e, 0x46, 0xbb, 0x0d, 0x91, 0x27, 0x00, 0x82, 0xad, 0x43, 0x53, 0xc7, 0x09, 0x12,
	0x2c, 0x44, 0xd9, 0x8b, 0x2c, 0x0e, 0x25, 0x43, 0xfb, 0x9e, 0xb6, 0x37, 0x48, 0xf0, 0x3d, 0x00,
	0x76, 0x2a, 0xc7, 0x58, 0xbf, 0x06, 0x10, 0xf5, 0xca, 0x77, 0x30, 0xc5, 0x43, 0x93, 0x62, 0xdd,
	0x50, 0x6a, 0x71, 0x82, 0x7f, 0x1c, 0x80, 0x26, 0xf5, 0x0d, 0xbd, 0xae, 0xd3, 0xd0, 0x7d, 0x18,
	0x60, 0x11, 0x6c, 0x48, 0x95, 0x41, 0x2f, 0x5f, 0x16, 0x6b, 0xd3, 0xf1, 0x06, 0x20, 0x04, 0xb6,
	0xc3, 0x38, 0x16, 0xfe, 0xf6, 0x89, 0x33, 0x1d, 0x51, 0xfc, 0x8d, 0x5d, 0x2b, 0xca, 0x7b, 0x32,
	0x68, 0x83, 0x4a, 0x05, 0x0d, 0xf0, 0xfe, 0x3a, 0xcc, 0x7f, 0x45, 0x15, 0x8c, 0x68, 0x17, 0x56,
	0x91, 0x27, 0x69, 0xcc, 0xde, 0x63, 0xf7, 0x5d, 0xaa, 0x17, 0xc1, 0x02, 0x26, 0x76, 0x6b, 0xff,
	0xaf, 0x38, 0x83, 0x19, 0xec, 0xfd, 0x5c, 0xc8, 0x0f, 0x39, 0x28, 0xf8, 0xcb, 0x81, 0xc9, 0x73,
	0x75, 0x19, 0x9f, 0xcf, 0x22, 0x99, 0xf0, 0x94, 0x9c, 0x82, 0x97, 0xcb, 0x50, 0x48, 0xec, 0xc5,
	0xf8, 0x9c, 0x98, 0x3e, 0x6a, 0xce, 0x6b, 0x65, 0xb9, 0xde, 0xa2, 0x9a, 0x42, 0xbe, 0x84, 0xed,
	0x58, 0x84, 0xef, 0xb0, 0x35, 0xe3, 0xf3, 0xe3, 0x16, 0xf5, 0x45, 0x11, 0xbd, 0x29, 0x7f, 0x10,
	0xe1, 0xbb, 0xeb, 0x2d, 0x8a, 0x2c, 0x72, 0x0a, 0xee, 0xbc, 0x28, 0x31, 0xac, 0x2e, 0xf9, 0xb2,
	0x4a, 0xeb, 0x7a, 0x8b, 0x2a, 0x12, 0xd9, 0x87, 0x81, 0x2c, 0x31, 0x50, 0x8f, 0x0e, 0x64, 0x79,
	0xb9, 0x03, 0xde, 0xdb, 0x70, 0x55, 0xb0, 0xe0, 0x53, 0x18, 0x5b, 0xa1, 0xf4, 0x2b, 0x27, 0xf8,
	0x1c, 0x0e, 0x3a, 0x41, 0x6c, 0x20, 0x7e, 0x55, 0x11, 0xeb, 0x00, 0x1e, 0x2e, 0x61, 0x70, 0x0a,
	0xe4, 0x55, 0xc1, 0x44, 0x69, 0x76, 0x95, 0x28, 0xef, 0x0d, 0xce, 0x8f, 0xe1, 0x91, 0xc5, 0x7d,
	0x11, 0xe6, 0x12, 0xd9, 0xc1, 0x0a, 0x8e, 0x6d, 0x3c, 0xc9, 0x65, 0xe5, 0xe7, 0x09, 0x00, 0x16,
	0x96, 0x5a, 0xce, 0x2c, 0x44, 0x9d, 0x13, 0xe1, 0x95, 0x1e, 0x60, 0x61, 0xf4, 0x42, 0x45, 0x1c,
	0x27, 0x82, 0x61, 0xfb, 0x50, 0x27, 0x1e, 0x6d, 0x80, 0xe0, 0x17, 0x78, 0x8c, 0xa7, 0x5d, 0x16,
	0x25, 0x65, 0x11, 0x17, 0xb1, 0x39, 0x6c, 0x96, 0xc6, 0x33, 0xa5, 0xb4, 0xfe, 0xbb, 0x57, 0x49,
	0x65, 0x60, 0x69, 0xb2, 0xd6, 0xba, 0x6b, 0x6b, 0xfd, 0x06, 0x3e, 0x41, 0xff, 0x8d, 0x0a, 0xff,
	0xeb, 0x01, 0xc1, 0x1a, 0xf6, 0xd0, 0x95, 0xda, 0xf6, 0xc0, 0xbb, 0xb0, 0x21, 0x36, 0x5d, 0x19,
	0x77, 0x63, 0x65, 0xb6, 0xbb, 0x95, 0x79, 0x59, 0x29, 0x5f, 0xd7, 0xa5, 0xf6, 0xeb, 0xf4, 0xe5,
	0x3c, 0xb0, 0x72, 0x6e, 0xe2, 0x72, 0xed, 0x7e, 0x4f, 0xe1, 0xd0, 0x92, 0xe6, 0x43, 0xca, 0xa8,
	0xf5, 0xa9, 0xa4, 0xf9, 0x10, 0xf1, 0x95, 0xa5, 0x4f, 0x13, 0xe5, 0x87, 0xf6, 0xeb, 0x3b, 0x38,
	0xa0, 0x2c, 0x5b, 0x59, 0xea, 0x23, 0x53, 0x18, 0xea, 0xb7, 0x79, 0xe3, 0xdb, 0x6d, 0xec, 0xc1,
	0x05, 0x8c, 0xad, 0xcd, 0xe4, 0xa9, 0x1d, 0x4b, 0xdf, 0x3e, 0x93, 0xc6, 0x15, 0xec, 0xe3, 0xb6,
	0x26, 0x8b, 0x6f, 0xd4, 0x07, 0x48, 0xfd, 0x52, 0x01, 0x98, 0x63, 0x8f, 0xcc, 0x76, 0xeb, 0x9b,
	0x68, 0x91, 0x82, 0x0b, 0xd8, 0x45, 0x27, 0x3f, 0xb1, 0x92, 0x7c, 0x01, 0x43, 0x7d, 0x27, 0xcd,
	0xc9, 0x3d, 0x5b, 0x0d, 0x41, 0x75, 0x05, 0xb7, 0xdd, 0x59, 0x9f, 0xbf, 0x5a, 0x2d, 0xa6, 0x86,
	0xb8, 0x08, 0xae, 0xe1, 0x08, 0x99, 0x95, 0xfc, 0xb0, 0x36, 0xcf, 0x60, 0x12, 0x5a, 0x6b, 0x13,
	0xea, 0x81, 0x39, 0xaf, 0xa2, 0xd2, 0x16, 0x29, 0xf8, 0xdb, 0x81, 0xdd, 0x5a, 0xc4, 0x7d, 0xb2,
	0x6a, 0x3d, 0x32, 0x83, 0xee, 0x3b, 0xfd, 0x31, 0xec, 0xce, 0x8b, 0xf2, 0xaa, 0xd6, 0xb3, 0x4b,
	0xeb, 0x75, 0xd3, 0xfe, 0xed, 0xce, 0x58, 0x24, 0xb9, 0x0c, 0x57, 0x57, 0x3c, 0x97, 0xf8, 0x04,
	0x38, 0xb4, 0x01, 0xd4, 0xc7, 0xa4, 0x9a, 0x2d, 0x2e, 0xd5, 0x08, 0x61, 0x46, 0x9a, 0x36, 0x18,
	0xfc, 0xe1, 0xc0, 0x1e, 0x65, 0x11, 0x4b, 0x32, 0x69, 0xda, 0xbb, 0xe1, 0x42, 0xe8, 0xf3, 0x07,
	0xf6, 0xf9, 0xbd, 0x52, 0x23, 0xc7, 0x30, 0x0c, 0x9b, 0xbb, 0xe7, 0x52, 0xb3, 0x6a, 0xe5, 0xe7,
	0x75, 0xf2, 0x6b, 0x55, 0x66, 0xd8, 0x7d, 0x7e, 0x7f, 0xf7, 0x60, 0x78, 0xc5, 0xd3, 0x45, 0xb2,
	0x54, 0xd3, 0xc1, 0x3a, 0x4c, 0xc3, 0x25, 0x13, 0xb3, 0x26, 0x46, 0x1b, 0x52, 0x69, 0xc7, 0xec,
	0x2d, 0x5b, 0xf1, 0xcc, 0x70, 0xf4, 0xe5, 0x68, 0x83, 0xca, 0x4f, 0x16, 0x0a, 0x99, 0x1a, 0x8e,
	0xab, 0xfd, 0x58, 0x90, 0x9a, 0x1d, 0x17, 0x89, 0xc8, 0xd5, 0xcc, 0xf1, 0x1b, 0x9b, 0x35, 0x1f,
	0xd0, 0x0e, 0x4a, 0xce, 0x80, 0xe4, 0x2c, 0xe2, 0x69, 0x1c, 0x8a, 0xb2, 0xe1, 0x7a, 0xc8, 0xed,
	0xb1, 0xa8, 0xf8, 0x32, 0xc1, 0xd7, 0x5c, 0xd5, 0x04, 0xa9, 0x7a, 0xc6, 0x68, 0x83, 0x6a, 0x16,
	0xc9, 0x8b, 0x2c, 0xe3, 0x42, 0xfe, 0x58, 0xe8, 0x17, 0x15, 0x67, 0x8d, 0x11, 0xed, 0xc2, 0xed,
	0x38, 0x6f, 0x99, 0x88, 0xfc, 0x5d, 0xec, 0x73, 0x07, 0xbd, 0x1f, 0x27, 0x72, 0xf5, 0x8c, 0xd9,
	0x63, 0xc1, 0x38, 0x2b, 0x95, 0x20, 0x15, 0xb4, 0x7c, 0x5a, 0xa0, 0xaa, 0xa3, 0x15, 0x10, 0x0e,
	0x9d, 0x0e, 0xb5, 0x21, 0x35, 0x9d, 0x9b, 0xb2, 0xe2, 0xc4, 0xe9, 0xd0, 0x6a, 0x89, 0xef, 0x74,
	0xd5, 0x14, 0x9c, 0x36, 0x1d, 0xda, 0x00, 0xed, 0x51, 0x78, 0xbf, 0x67, 0x14, 0xae, 0x0b, 0xe6,
	0x1f, 0x68, 0x6b, 0x0d, 0x28, 0xa9, 0xad, 0x92, 0x85, 0x1e, 0x63, 0x0f, 0xb5, 0xd4, 0xaa, 0xb5,
	0xaa, 0x97, 0x34, 0xef, 0x45, 0x24, 0x90, 0x71, 0xa4, 0xff, 0x13, 0xb4, 0xd1, 0xee, 0x1c, 0x4a,
	0xee, 0xcd, 0xa1, 0xf3, 0x21, 0xfe, 0x8f, 0x79, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10,
	0xa4, 0x9a, 0xb1, 0xd7, 0x0c, 0x00, 0x00,
}
