// Code generated by protoc-gen-go. DO NOT EDIT.
// source: f3d.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoundInfo struct {
	// 游戏轮次
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本轮游戏开始事件
	BeginTime int64 `protobuf:"varint,2,opt,name=beginTime,proto3" json:"beginTime,omitempty"`
	// 本轮游戏结束时间
	EndTime int64 `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	// 本轮游戏目前为止最后一把钥匙持有人（游戏开奖时，这个就是中奖人）
	LastOwner string `protobuf:"bytes,4,opt,name=lastOwner,proto3" json:"lastOwner,omitempty"`
	// 最后一把钥匙的购买时间
	LastKeyTime int64 `protobuf:"varint,5,opt,name=lastKeyTime,proto3" json:"lastKeyTime,omitempty"`
	// 最后一把钥匙的价格
	LastKeyPrice float32 `protobuf:"fixed32,6,opt,name=lastKeyPrice,proto3" json:"lastKeyPrice,omitempty"`
	// 本轮游戏奖金池总额
	BonusPool float32 `protobuf:"fixed32,7,opt,name=bonusPool,proto3" json:"bonusPool,omitempty"`
	// 本轮游戏参与地址数
	UserCount int64 `protobuf:"varint,8,opt,name=userCount,proto3" json:"userCount,omitempty"`
	// 本轮游戏募集到的key个数
	KeyCount int64 `protobuf:"varint,9,opt,name=keyCount,proto3" json:"keyCount,omitempty"`
	// 距离开奖剩余时间
	RemainTime           int64    `protobuf:"varint,10,opt,name=remainTime,proto3" json:"remainTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundInfo) Reset()         { *m = RoundInfo{} }
func (m *RoundInfo) String() string { return proto.CompactTextString(m) }
func (*RoundInfo) ProtoMessage()    {}
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{0}
}
func (m *RoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfo.Unmarshal(m, b)
}
func (m *RoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfo.Marshal(b, m, deterministic)
}
func (dst *RoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfo.Merge(dst, src)
}
func (m *RoundInfo) XXX_Size() int {
	return xxx_messageInfo_RoundInfo.Size(m)
}
func (m *RoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfo proto.InternalMessageInfo

func (m *RoundInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *RoundInfo) GetBeginTime() int64 {
	if m != nil {
		return m.BeginTime
	}
	return 0
}

func (m *RoundInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoundInfo) GetLastOwner() string {
	if m != nil {
		return m.LastOwner
	}
	return ""
}

func (m *RoundInfo) GetLastKeyTime() int64 {
	if m != nil {
		return m.LastKeyTime
	}
	return 0
}

func (m *RoundInfo) GetLastKeyPrice() float32 {
	if m != nil {
		return m.LastKeyPrice
	}
	return 0
}

func (m *RoundInfo) GetBonusPool() float32 {
	if m != nil {
		return m.BonusPool
	}
	return 0
}

func (m *RoundInfo) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *RoundInfo) GetKeyCount() int64 {
	if m != nil {
		return m.KeyCount
	}
	return 0
}

func (m *RoundInfo) GetRemainTime() int64 {
	if m != nil {
		return m.RemainTime
	}
	return 0
}

func (m *RoundInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type RoundsInfo struct {
	RoundsInfo           []*RoundInfo `protobuf:"bytes,1,rep,name=roundsInfo,proto3" json:"roundsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RoundsInfo) Reset()         { *m = RoundsInfo{} }
func (m *RoundsInfo) String() string { return proto.CompactTextString(m) }
func (*RoundsInfo) ProtoMessage()    {}
func (*RoundsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{1}
}
func (m *RoundsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundsInfo.Unmarshal(m, b)
}
func (m *RoundsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundsInfo.Marshal(b, m, deterministic)
}
func (dst *RoundsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundsInfo.Merge(dst, src)
}
func (m *RoundsInfo) XXX_Size() int {
	return xxx_messageInfo_RoundsInfo.Size(m)
}
func (m *RoundsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundsInfo proto.InternalMessageInfo

func (m *RoundsInfo) GetRoundsInfo() []*RoundInfo {
	if m != nil {
		return m.RoundsInfo
	}
	return nil
}

type KeyInfo struct {
	// 游戏轮次  (是由系统合约填写后存储）
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 本次购买key的价格 (是由系统合约填写后存储）
	KeyPrice float32 `protobuf:"fixed32,2,opt,name=keyPrice,proto3" json:"keyPrice,omitempty"`
	// 用户本次买的key的数量
	KeyNum int64 `protobuf:"varint,3,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	// 用户地址 (是由系统合约填写后存储）
	Addr string `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// 交易确认存储时间（被打包的时间）
	BuyKeyTime int64 `protobuf:"varint,5,opt,name=buyKeyTime,proto3" json:"buyKeyTime,omitempty"`
	// 买票的txHash
	BuyKeyTxHash         string   `protobuf:"bytes,6,opt,name=buyKeyTxHash,proto3" json:"buyKeyTxHash,omitempty"`
	Index                int64    `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyInfo) Reset()         { *m = KeyInfo{} }
func (m *KeyInfo) String() string { return proto.CompactTextString(m) }
func (*KeyInfo) ProtoMessage()    {}
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{2}
}
func (m *KeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyInfo.Unmarshal(m, b)
}
func (m *KeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyInfo.Marshal(b, m, deterministic)
}
func (dst *KeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyInfo.Merge(dst, src)
}
func (m *KeyInfo) XXX_Size() int {
	return xxx_messageInfo_KeyInfo.Size(m)
}
func (m *KeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KeyInfo proto.InternalMessageInfo

func (m *KeyInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *KeyInfo) GetKeyPrice() float32 {
	if m != nil {
		return m.KeyPrice
	}
	return 0
}

func (m *KeyInfo) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

func (m *KeyInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *KeyInfo) GetBuyKeyTime() int64 {
	if m != nil {
		return m.BuyKeyTime
	}
	return 0
}

func (m *KeyInfo) GetBuyKeyTxHash() string {
	if m != nil {
		return m.BuyKeyTxHash
	}
	return ""
}

func (m *KeyInfo) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// message for execs.f3d
type F3DAction struct {
	// Types that are valid to be assigned to Value:
	//	*F3DAction_Start
	//	*F3DAction_Draw
	//	*F3DAction_Buy
	Value                isF3DAction_Value `protobuf_oneof:"value"`
	Ty                   int32             `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *F3DAction) Reset()         { *m = F3DAction{} }
func (m *F3DAction) String() string { return proto.CompactTextString(m) }
func (*F3DAction) ProtoMessage()    {}
func (*F3DAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{3}
}
func (m *F3DAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DAction.Unmarshal(m, b)
}
func (m *F3DAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DAction.Marshal(b, m, deterministic)
}
func (dst *F3DAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DAction.Merge(dst, src)
}
func (m *F3DAction) XXX_Size() int {
	return xxx_messageInfo_F3DAction.Size(m)
}
func (m *F3DAction) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DAction.DiscardUnknown(m)
}

var xxx_messageInfo_F3DAction proto.InternalMessageInfo

type isF3DAction_Value interface {
	isF3DAction_Value()
}

type F3DAction_Start struct {
	Start *F3DStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}
type F3DAction_Draw struct {
	Draw *F3DLuckyDraw `protobuf:"bytes,2,opt,name=draw,proto3,oneof"`
}
type F3DAction_Buy struct {
	Buy *F3DBuyKey `protobuf:"bytes,3,opt,name=buy,proto3,oneof"`
}

func (*F3DAction_Start) isF3DAction_Value() {}
func (*F3DAction_Draw) isF3DAction_Value()  {}
func (*F3DAction_Buy) isF3DAction_Value()   {}

func (m *F3DAction) GetValue() isF3DAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *F3DAction) GetStart() *F3DStart {
	if x, ok := m.GetValue().(*F3DAction_Start); ok {
		return x.Start
	}
	return nil
}

func (m *F3DAction) GetDraw() *F3DLuckyDraw {
	if x, ok := m.GetValue().(*F3DAction_Draw); ok {
		return x.Draw
	}
	return nil
}

func (m *F3DAction) GetBuy() *F3DBuyKey {
	if x, ok := m.GetValue().(*F3DAction_Buy); ok {
		return x.Buy
	}
	return nil
}

func (m *F3DAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*F3DAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _F3DAction_OneofMarshaler, _F3DAction_OneofUnmarshaler, _F3DAction_OneofSizer, []interface{}{
		(*F3DAction_Start)(nil),
		(*F3DAction_Draw)(nil),
		(*F3DAction_Buy)(nil),
	}
}

func _F3DAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*F3DAction)
	// value
	switch x := m.Value.(type) {
	case *F3DAction_Start:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Start); err != nil {
			return err
		}
	case *F3DAction_Draw:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Draw); err != nil {
			return err
		}
	case *F3DAction_Buy:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Buy); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("F3DAction.Value has unexpected type %T", x)
	}
	return nil
}

func _F3DAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*F3DAction)
	switch tag {
	case 1: // value.start
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DStart)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Start{msg}
		return true, err
	case 2: // value.draw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DLuckyDraw)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Draw{msg}
		return true, err
	case 3: // value.buy
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(F3DBuyKey)
		err := b.DecodeMessage(msg)
		m.Value = &F3DAction_Buy{msg}
		return true, err
	default:
		return false, nil
	}
}

func _F3DAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*F3DAction)
	// value
	switch x := m.Value.(type) {
	case *F3DAction_Start:
		s := proto.Size(x.Start)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *F3DAction_Draw:
		s := proto.Size(x.Draw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *F3DAction_Buy:
		s := proto.Size(x.Buy)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type F3DStart struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DStart) Reset()         { *m = F3DStart{} }
func (m *F3DStart) String() string { return proto.CompactTextString(m) }
func (*F3DStart) ProtoMessage()    {}
func (*F3DStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{4}
}
func (m *F3DStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DStart.Unmarshal(m, b)
}
func (m *F3DStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DStart.Marshal(b, m, deterministic)
}
func (dst *F3DStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DStart.Merge(dst, src)
}
func (m *F3DStart) XXX_Size() int {
	return xxx_messageInfo_F3DStart.Size(m)
}
func (m *F3DStart) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DStart.DiscardUnknown(m)
}

var xxx_messageInfo_F3DStart proto.InternalMessageInfo

func (m *F3DStart) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DLuckyDraw struct {
	// 轮次，这个填不填不重要，合约里面会自动校验的
	Round                int64    `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DLuckyDraw) Reset()         { *m = F3DLuckyDraw{} }
func (m *F3DLuckyDraw) String() string { return proto.CompactTextString(m) }
func (*F3DLuckyDraw) ProtoMessage()    {}
func (*F3DLuckyDraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{5}
}
func (m *F3DLuckyDraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DLuckyDraw.Unmarshal(m, b)
}
func (m *F3DLuckyDraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DLuckyDraw.Marshal(b, m, deterministic)
}
func (dst *F3DLuckyDraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DLuckyDraw.Merge(dst, src)
}
func (m *F3DLuckyDraw) XXX_Size() int {
	return xxx_messageInfo_F3DLuckyDraw.Size(m)
}
func (m *F3DLuckyDraw) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DLuckyDraw.DiscardUnknown(m)
}

var xxx_messageInfo_F3DLuckyDraw proto.InternalMessageInfo

func (m *F3DLuckyDraw) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DBuyKey struct {
	// 用户本次买的key的数量
	KeyNum               int64    `protobuf:"varint,3,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DBuyKey) Reset()         { *m = F3DBuyKey{} }
func (m *F3DBuyKey) String() string { return proto.CompactTextString(m) }
func (*F3DBuyKey) ProtoMessage()    {}
func (*F3DBuyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{6}
}
func (m *F3DBuyKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DBuyKey.Unmarshal(m, b)
}
func (m *F3DBuyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DBuyKey.Marshal(b, m, deterministic)
}
func (dst *F3DBuyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DBuyKey.Merge(dst, src)
}
func (m *F3DBuyKey) XXX_Size() int {
	return xxx_messageInfo_F3DBuyKey.Size(m)
}
func (m *F3DBuyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DBuyKey.DiscardUnknown(m)
}

var xxx_messageInfo_F3DBuyKey proto.InternalMessageInfo

func (m *F3DBuyKey) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

// 查询f3d 游戏信息,这里面其实包含了key的最新价格信息
type QueryF3DByRound struct {
	// 轮次，默认查询最新的
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryF3DByRound) Reset()         { *m = QueryF3DByRound{} }
func (m *QueryF3DByRound) String() string { return proto.CompactTextString(m) }
func (*QueryF3DByRound) ProtoMessage()    {}
func (*QueryF3DByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{7}
}
func (m *QueryF3DByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryF3DByRound.Unmarshal(m, b)
}
func (m *QueryF3DByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryF3DByRound.Marshal(b, m, deterministic)
}
func (dst *QueryF3DByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryF3DByRound.Merge(dst, src)
}
func (m *QueryF3DByRound) XXX_Size() int {
	return xxx_messageInfo_QueryF3DByRound.Size(m)
}
func (m *QueryF3DByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryF3DByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryF3DByRound proto.InternalMessageInfo

func (m *QueryF3DByRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type QueryF3DLastRound struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryF3DLastRound) Reset()         { *m = QueryF3DLastRound{} }
func (m *QueryF3DLastRound) String() string { return proto.CompactTextString(m) }
func (*QueryF3DLastRound) ProtoMessage()    {}
func (*QueryF3DLastRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{8}
}
func (m *QueryF3DLastRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryF3DLastRound.Unmarshal(m, b)
}
func (m *QueryF3DLastRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryF3DLastRound.Marshal(b, m, deterministic)
}
func (dst *QueryF3DLastRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryF3DLastRound.Merge(dst, src)
}
func (m *QueryF3DLastRound) XXX_Size() int {
	return xxx_messageInfo_QueryF3DLastRound.Size(m)
}
func (m *QueryF3DLastRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryF3DLastRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryF3DLastRound proto.InternalMessageInfo

type QueryF3DListByRound struct {
	// 轮次，默认查询最新的
	StartRound int64 `protobuf:"varint,1,opt,name=startRound,proto3" json:"startRound,omitempty"`
	// 单页返回多少条记录，默认返回10条，单次最多返回50条
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryF3DListByRound) Reset()         { *m = QueryF3DListByRound{} }
func (m *QueryF3DListByRound) String() string { return proto.CompactTextString(m) }
func (*QueryF3DListByRound) ProtoMessage()    {}
func (*QueryF3DListByRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{9}
}
func (m *QueryF3DListByRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryF3DListByRound.Unmarshal(m, b)
}
func (m *QueryF3DListByRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryF3DListByRound.Marshal(b, m, deterministic)
}
func (dst *QueryF3DListByRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryF3DListByRound.Merge(dst, src)
}
func (m *QueryF3DListByRound) XXX_Size() int {
	return xxx_messageInfo_QueryF3DListByRound.Size(m)
}
func (m *QueryF3DListByRound) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryF3DListByRound.DiscardUnknown(m)
}

var xxx_messageInfo_QueryF3DListByRound proto.InternalMessageInfo

func (m *QueryF3DListByRound) GetStartRound() int64 {
	if m != nil {
		return m.StartRound
	}
	return 0
}

func (m *QueryF3DListByRound) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryF3DListByRound) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// key 信息查询
type QueryBuyRecordByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBuyRecordByRoundAndAddr) Reset()         { *m = QueryBuyRecordByRoundAndAddr{} }
func (m *QueryBuyRecordByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryBuyRecordByRoundAndAddr) ProtoMessage()    {}
func (*QueryBuyRecordByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{10}
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryBuyRecordByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Merge(dst, src)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryBuyRecordByRoundAndAddr.Size(m)
}
func (m *QueryBuyRecordByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBuyRecordByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBuyRecordByRoundAndAddr proto.InternalMessageInfo

func (m *QueryBuyRecordByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryBuyRecordByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *QueryBuyRecordByRoundAndAddr) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 用户key数量查询
type QueryKeyCountByRoundAndAddr struct {
	// 轮次,必填参数
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// 用户地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryKeyCountByRoundAndAddr) Reset()         { *m = QueryKeyCountByRoundAndAddr{} }
func (m *QueryKeyCountByRoundAndAddr) String() string { return proto.CompactTextString(m) }
func (*QueryKeyCountByRoundAndAddr) ProtoMessage()    {}
func (*QueryKeyCountByRoundAndAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{11}
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Unmarshal(m, b)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Marshal(b, m, deterministic)
}
func (dst *QueryKeyCountByRoundAndAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKeyCountByRoundAndAddr.Merge(dst, src)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_Size() int {
	return xxx_messageInfo_QueryKeyCountByRoundAndAddr.Size(m)
}
func (m *QueryKeyCountByRoundAndAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKeyCountByRoundAndAddr.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKeyCountByRoundAndAddr proto.InternalMessageInfo

func (m *QueryKeyCountByRoundAndAddr) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryKeyCountByRoundAndAddr) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type QueryAddrInfo struct {
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Direction            int32    `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAddrInfo) Reset()         { *m = QueryAddrInfo{} }
func (m *QueryAddrInfo) String() string { return proto.CompactTextString(m) }
func (*QueryAddrInfo) ProtoMessage()    {}
func (*QueryAddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{12}
}
func (m *QueryAddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAddrInfo.Unmarshal(m, b)
}
func (m *QueryAddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAddrInfo.Marshal(b, m, deterministic)
}
func (dst *QueryAddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddrInfo.Merge(dst, src)
}
func (m *QueryAddrInfo) XXX_Size() int {
	return xxx_messageInfo_QueryAddrInfo.Size(m)
}
func (m *QueryAddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddrInfo proto.InternalMessageInfo

func (m *QueryAddrInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryAddrInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *QueryAddrInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryAddrInfo) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type F3DRecord struct {
	// 用户地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// index
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// round
	Round                int64    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DRecord) Reset()         { *m = F3DRecord{} }
func (m *F3DRecord) String() string { return proto.CompactTextString(m) }
func (*F3DRecord) ProtoMessage()    {}
func (*F3DRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{13}
}
func (m *F3DRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DRecord.Unmarshal(m, b)
}
func (m *F3DRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DRecord.Marshal(b, m, deterministic)
}
func (dst *F3DRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DRecord.Merge(dst, src)
}
func (m *F3DRecord) XXX_Size() int {
	return xxx_messageInfo_F3DRecord.Size(m)
}
func (m *F3DRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DRecord.DiscardUnknown(m)
}

var xxx_messageInfo_F3DRecord proto.InternalMessageInfo

func (m *F3DRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *F3DRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *F3DRecord) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DStartRound struct {
	// round
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DStartRound) Reset()         { *m = F3DStartRound{} }
func (m *F3DStartRound) String() string { return proto.CompactTextString(m) }
func (*F3DStartRound) ProtoMessage()    {}
func (*F3DStartRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{14}
}
func (m *F3DStartRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DStartRound.Unmarshal(m, b)
}
func (m *F3DStartRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DStartRound.Marshal(b, m, deterministic)
}
func (dst *F3DStartRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DStartRound.Merge(dst, src)
}
func (m *F3DStartRound) XXX_Size() int {
	return xxx_messageInfo_F3DStartRound.Size(m)
}
func (m *F3DStartRound) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DStartRound.DiscardUnknown(m)
}

var xxx_messageInfo_F3DStartRound proto.InternalMessageInfo

func (m *F3DStartRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DDrawRound struct {
	// round
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DDrawRound) Reset()         { *m = F3DDrawRound{} }
func (m *F3DDrawRound) String() string { return proto.CompactTextString(m) }
func (*F3DDrawRound) ProtoMessage()    {}
func (*F3DDrawRound) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{15}
}
func (m *F3DDrawRound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DDrawRound.Unmarshal(m, b)
}
func (m *F3DDrawRound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DDrawRound.Marshal(b, m, deterministic)
}
func (dst *F3DDrawRound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DDrawRound.Merge(dst, src)
}
func (m *F3DDrawRound) XXX_Size() int {
	return xxx_messageInfo_F3DDrawRound.Size(m)
}
func (m *F3DDrawRound) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DDrawRound.DiscardUnknown(m)
}

var xxx_messageInfo_F3DDrawRound proto.InternalMessageInfo

func (m *F3DDrawRound) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type F3DBuyRecord struct {
	Round                int64    `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *F3DBuyRecord) Reset()         { *m = F3DBuyRecord{} }
func (m *F3DBuyRecord) String() string { return proto.CompactTextString(m) }
func (*F3DBuyRecord) ProtoMessage()    {}
func (*F3DBuyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{16}
}
func (m *F3DBuyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_F3DBuyRecord.Unmarshal(m, b)
}
func (m *F3DBuyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_F3DBuyRecord.Marshal(b, m, deterministic)
}
func (dst *F3DBuyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_F3DBuyRecord.Merge(dst, src)
}
func (m *F3DBuyRecord) XXX_Size() int {
	return xxx_messageInfo_F3DBuyRecord.Size(m)
}
func (m *F3DBuyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_F3DBuyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_F3DBuyRecord proto.InternalMessageInfo

func (m *F3DBuyRecord) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *F3DBuyRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *F3DBuyRecord) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// f3d round查询返回数据
type ReplyF3DList struct {
	Rounds               []*RoundInfo `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyF3DList) Reset()         { *m = ReplyF3DList{} }
func (m *ReplyF3DList) String() string { return proto.CompactTextString(m) }
func (*ReplyF3DList) ProtoMessage()    {}
func (*ReplyF3DList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{17}
}
func (m *ReplyF3DList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyF3DList.Unmarshal(m, b)
}
func (m *ReplyF3DList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyF3DList.Marshal(b, m, deterministic)
}
func (dst *ReplyF3DList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyF3DList.Merge(dst, src)
}
func (m *ReplyF3DList) XXX_Size() int {
	return xxx_messageInfo_ReplyF3DList.Size(m)
}
func (m *ReplyF3DList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyF3DList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyF3DList proto.InternalMessageInfo

func (m *ReplyF3DList) GetRounds() []*RoundInfo {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type ReplyF3D struct {
	Round                *RoundInfo `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyF3D) Reset()         { *m = ReplyF3D{} }
func (m *ReplyF3D) String() string { return proto.CompactTextString(m) }
func (*ReplyF3D) ProtoMessage()    {}
func (*ReplyF3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{18}
}
func (m *ReplyF3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyF3D.Unmarshal(m, b)
}
func (m *ReplyF3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyF3D.Marshal(b, m, deterministic)
}
func (dst *ReplyF3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyF3D.Merge(dst, src)
}
func (m *ReplyF3D) XXX_Size() int {
	return xxx_messageInfo_ReplyF3D.Size(m)
}
func (m *ReplyF3D) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyF3D.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyF3D proto.InternalMessageInfo

func (m *ReplyF3D) GetRound() *RoundInfo {
	if m != nil {
		return m.Round
	}
	return nil
}

// 用户查询买的key信息返回数据
type ReplyBuyRecord struct {
	RecordList           []*KeyInfo `protobuf:"bytes,1,rep,name=recordList,proto3" json:"recordList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyBuyRecord) Reset()         { *m = ReplyBuyRecord{} }
func (m *ReplyBuyRecord) String() string { return proto.CompactTextString(m) }
func (*ReplyBuyRecord) ProtoMessage()    {}
func (*ReplyBuyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{19}
}
func (m *ReplyBuyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBuyRecord.Unmarshal(m, b)
}
func (m *ReplyBuyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBuyRecord.Marshal(b, m, deterministic)
}
func (dst *ReplyBuyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBuyRecord.Merge(dst, src)
}
func (m *ReplyBuyRecord) XXX_Size() int {
	return xxx_messageInfo_ReplyBuyRecord.Size(m)
}
func (m *ReplyBuyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBuyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBuyRecord proto.InternalMessageInfo

func (m *ReplyBuyRecord) GetRecordList() []*KeyInfo {
	if m != nil {
		return m.RecordList
	}
	return nil
}

type ReplyKey struct {
	Key                  *KeyInfo `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyKey) Reset()         { *m = ReplyKey{} }
func (m *ReplyKey) String() string { return proto.CompactTextString(m) }
func (*ReplyKey) ProtoMessage()    {}
func (*ReplyKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{20}
}
func (m *ReplyKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKey.Unmarshal(m, b)
}
func (m *ReplyKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKey.Marshal(b, m, deterministic)
}
func (dst *ReplyKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKey.Merge(dst, src)
}
func (m *ReplyKey) XXX_Size() int {
	return xxx_messageInfo_ReplyKey.Size(m)
}
func (m *ReplyKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKey proto.InternalMessageInfo

func (m *ReplyKey) GetKey() *KeyInfo {
	if m != nil {
		return m.Key
	}
	return nil
}

type ReplyKeyCount struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyKeyCount) Reset()         { *m = ReplyKeyCount{} }
func (m *ReplyKeyCount) String() string { return proto.CompactTextString(m) }
func (*ReplyKeyCount) ProtoMessage()    {}
func (*ReplyKeyCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{21}
}
func (m *ReplyKeyCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKeyCount.Unmarshal(m, b)
}
func (m *ReplyKeyCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKeyCount.Marshal(b, m, deterministic)
}
func (dst *ReplyKeyCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKeyCount.Merge(dst, src)
}
func (m *ReplyKeyCount) XXX_Size() int {
	return xxx_messageInfo_ReplyKeyCount.Size(m)
}
func (m *ReplyKeyCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKeyCount.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKeyCount proto.InternalMessageInfo

func (m *ReplyKeyCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReplyAddrInfoList struct {
	AddrInfoList         []*AddrInfo `protobuf:"bytes,1,rep,name=addrInfoList,proto3" json:"addrInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplyAddrInfoList) Reset()         { *m = ReplyAddrInfoList{} }
func (m *ReplyAddrInfoList) String() string { return proto.CompactTextString(m) }
func (*ReplyAddrInfoList) ProtoMessage()    {}
func (*ReplyAddrInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{22}
}
func (m *ReplyAddrInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAddrInfoList.Unmarshal(m, b)
}
func (m *ReplyAddrInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAddrInfoList.Marshal(b, m, deterministic)
}
func (dst *ReplyAddrInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAddrInfoList.Merge(dst, src)
}
func (m *ReplyAddrInfoList) XXX_Size() int {
	return xxx_messageInfo_ReplyAddrInfoList.Size(m)
}
func (m *ReplyAddrInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAddrInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAddrInfoList proto.InternalMessageInfo

func (m *ReplyAddrInfoList) GetAddrInfoList() []*AddrInfo {
	if m != nil {
		return m.AddrInfoList
	}
	return nil
}

type AddrInfo struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	KeyNum               int64    `protobuf:"varint,2,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	BuyCount             int64    `protobuf:"varint,3,opt,name=buyCount,proto3" json:"buyCount,omitempty"`
	Round                int64    `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	TotalCost            float32  `protobuf:"fixed32,5,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	Bonus                float32  `protobuf:"fixed32,6,opt,name=bonus,proto3" json:"bonus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrInfo) Reset()         { *m = AddrInfo{} }
func (m *AddrInfo) String() string { return proto.CompactTextString(m) }
func (*AddrInfo) ProtoMessage()    {}
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{23}
}
func (m *AddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrInfo.Unmarshal(m, b)
}
func (m *AddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrInfo.Marshal(b, m, deterministic)
}
func (dst *AddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrInfo.Merge(dst, src)
}
func (m *AddrInfo) XXX_Size() int {
	return xxx_messageInfo_AddrInfo.Size(m)
}
func (m *AddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddrInfo proto.InternalMessageInfo

func (m *AddrInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AddrInfo) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

func (m *AddrInfo) GetBuyCount() int64 {
	if m != nil {
		return m.BuyCount
	}
	return 0
}

func (m *AddrInfo) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *AddrInfo) GetTotalCost() float32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *AddrInfo) GetBonus() float32 {
	if m != nil {
		return m.Bonus
	}
	return 0
}

// 合约内部日志记录，待补全
type ReceiptF3D struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Round                int64    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Action               int64    `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`
	BuyCount             int64    `protobuf:"varint,5,opt,name=buyCount,proto3" json:"buyCount,omitempty"`
	KeyNum               int64    `protobuf:"varint,6,opt,name=keyNum,proto3" json:"keyNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptF3D) Reset()         { *m = ReceiptF3D{} }
func (m *ReceiptF3D) String() string { return proto.CompactTextString(m) }
func (*ReceiptF3D) ProtoMessage()    {}
func (*ReceiptF3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{24}
}
func (m *ReceiptF3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptF3D.Unmarshal(m, b)
}
func (m *ReceiptF3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptF3D.Marshal(b, m, deterministic)
}
func (dst *ReceiptF3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptF3D.Merge(dst, src)
}
func (m *ReceiptF3D) XXX_Size() int {
	return xxx_messageInfo_ReceiptF3D.Size(m)
}
func (m *ReceiptF3D) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptF3D.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptF3D proto.InternalMessageInfo

func (m *ReceiptF3D) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptF3D) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ReceiptF3D) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReceiptF3D) GetAction() int64 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ReceiptF3D) GetBuyCount() int64 {
	if m != nil {
		return m.BuyCount
	}
	return 0
}

func (m *ReceiptF3D) GetKeyNum() int64 {
	if m != nil {
		return m.KeyNum
	}
	return 0
}

type Config struct {
	Manager              string   `protobuf:"bytes,1,opt,name=manager,proto3" json:"manager,omitempty"`
	Developer            string   `protobuf:"bytes,2,opt,name=developer,proto3" json:"developer,omitempty"`
	WinnerBonus          float32  `protobuf:"fixed32,3,opt,name=winnerBonus,proto3" json:"winnerBonus,omitempty"`
	KeyBonus             float32  `protobuf:"fixed32,4,opt,name=keyBonus,proto3" json:"keyBonus,omitempty"`
	PoolBonus            float32  `protobuf:"fixed32,5,opt,name=poolBonus,proto3" json:"poolBonus,omitempty"`
	DeveloperBonus       float32  `protobuf:"fixed32,6,opt,name=developerBonus,proto3" json:"developerBonus,omitempty"`
	LifeTime             int64    `protobuf:"varint,7,opt,name=lifeTime,proto3" json:"lifeTime,omitempty"`
	KeyIncrTime          int64    `protobuf:"varint,8,opt,name=keyIncrTime,proto3" json:"keyIncrTime,omitempty"`
	MaxkeyIncrTime       int64    `protobuf:"varint,9,opt,name=maxkeyIncrTime,proto3" json:"maxkeyIncrTime,omitempty"`
	NouserDecrTime       int64    `protobuf:"varint,10,opt,name=nouserDecrTime,proto3" json:"nouserDecrTime,omitempty"`
	DrawDelayTime        int64    `protobuf:"varint,11,opt,name=drawDelayTime,proto3" json:"drawDelayTime,omitempty"`
	StartKeyPrice        float32  `protobuf:"fixed32,12,opt,name=startKeyPrice,proto3" json:"startKeyPrice,omitempty"`
	IncrKeyPrice         float32  `protobuf:"fixed32,13,opt,name=incrKeyPrice,proto3" json:"incrKeyPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3d_7aec159038704b46, []int{25}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *Config) GetDeveloper() string {
	if m != nil {
		return m.Developer
	}
	return ""
}

func (m *Config) GetWinnerBonus() float32 {
	if m != nil {
		return m.WinnerBonus
	}
	return 0
}

func (m *Config) GetKeyBonus() float32 {
	if m != nil {
		return m.KeyBonus
	}
	return 0
}

func (m *Config) GetPoolBonus() float32 {
	if m != nil {
		return m.PoolBonus
	}
	return 0
}

func (m *Config) GetDeveloperBonus() float32 {
	if m != nil {
		return m.DeveloperBonus
	}
	return 0
}

func (m *Config) GetLifeTime() int64 {
	if m != nil {
		return m.LifeTime
	}
	return 0
}

func (m *Config) GetKeyIncrTime() int64 {
	if m != nil {
		return m.KeyIncrTime
	}
	return 0
}

func (m *Config) GetMaxkeyIncrTime() int64 {
	if m != nil {
		return m.MaxkeyIncrTime
	}
	return 0
}

func (m *Config) GetNouserDecrTime() int64 {
	if m != nil {
		return m.NouserDecrTime
	}
	return 0
}

func (m *Config) GetDrawDelayTime() int64 {
	if m != nil {
		return m.DrawDelayTime
	}
	return 0
}

func (m *Config) GetStartKeyPrice() float32 {
	if m != nil {
		return m.StartKeyPrice
	}
	return 0
}

func (m *Config) GetIncrKeyPrice() float32 {
	if m != nil {
		return m.IncrKeyPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*RoundInfo)(nil), "types.RoundInfo")
	proto.RegisterType((*RoundsInfo)(nil), "types.RoundsInfo")
	proto.RegisterType((*KeyInfo)(nil), "types.KeyInfo")
	proto.RegisterType((*F3DAction)(nil), "types.F3dAction")
	proto.RegisterType((*F3DStart)(nil), "types.F3dStart")
	proto.RegisterType((*F3DLuckyDraw)(nil), "types.F3dLuckyDraw")
	proto.RegisterType((*F3DBuyKey)(nil), "types.F3dBuyKey")
	proto.RegisterType((*QueryF3DByRound)(nil), "types.QueryF3dByRound")
	proto.RegisterType((*QueryF3DLastRound)(nil), "types.QueryF3dLastRound")
	proto.RegisterType((*QueryF3DListByRound)(nil), "types.QueryF3dListByRound")
	proto.RegisterType((*QueryBuyRecordByRoundAndAddr)(nil), "types.QueryBuyRecordByRoundAndAddr")
	proto.RegisterType((*QueryKeyCountByRoundAndAddr)(nil), "types.QueryKeyCountByRoundAndAddr")
	proto.RegisterType((*QueryAddrInfo)(nil), "types.QueryAddrInfo")
	proto.RegisterType((*F3DRecord)(nil), "types.F3dRecord")
	proto.RegisterType((*F3DStartRound)(nil), "types.F3dStartRound")
	proto.RegisterType((*F3DDrawRound)(nil), "types.F3dDrawRound")
	proto.RegisterType((*F3DBuyRecord)(nil), "types.F3dBuyRecord")
	proto.RegisterType((*ReplyF3DList)(nil), "types.ReplyF3dList")
	proto.RegisterType((*ReplyF3D)(nil), "types.ReplyF3d")
	proto.RegisterType((*ReplyBuyRecord)(nil), "types.ReplyBuyRecord")
	proto.RegisterType((*ReplyKey)(nil), "types.ReplyKey")
	proto.RegisterType((*ReplyKeyCount)(nil), "types.ReplyKeyCount")
	proto.RegisterType((*ReplyAddrInfoList)(nil), "types.ReplyAddrInfoList")
	proto.RegisterType((*AddrInfo)(nil), "types.AddrInfo")
	proto.RegisterType((*ReceiptF3D)(nil), "types.ReceiptF3d")
	proto.RegisterType((*Config)(nil), "types.Config")
}

func init() { proto.RegisterFile("f3d.proto", fileDescriptor_f3d_7aec159038704b46) }

var fileDescriptor_f3d_7aec159038704b46 = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xce, 0xcc, 0xd8, 0x8e, 0x5d, 0x76, 0xb2, 0x6c, 0x07, 0x21, 0x6b, 0x89, 0x56, 0xd6, 0x10,
	0x76, 0x8d, 0x84, 0x22, 0x14, 0x5f, 0x38, 0x21, 0xe2, 0x44, 0xc1, 0x28, 0xab, 0x65, 0x69, 0x38,
	0x23, 0x8d, 0x3d, 0x9d, 0x30, 0xb2, 0x3d, 0x6d, 0xcd, 0x4f, 0x92, 0x79, 0x13, 0x0e, 0x88, 0x77,
	0x81, 0x77, 0xe0, 0x7d, 0x50, 0x55, 0xff, 0x4c, 0x8f, 0x65, 0xe7, 0xc0, 0xde, 0xa6, 0xbe, 0xaa,
	0x9a, 0xfa, 0xfb, 0xba, 0xbb, 0xa0, 0x77, 0x37, 0x89, 0xcf, 0x37, 0x99, 0x2c, 0x24, 0x6b, 0x17,
	0xd5, 0x46, 0xe4, 0xe1, 0xbf, 0x3e, 0xf4, 0xb8, 0x2c, 0xd3, 0xf8, 0xc7, 0xf4, 0x4e, 0xb2, 0x4f,
	0xa1, 0x9d, 0xa1, 0x30, 0xf4, 0x46, 0xde, 0x38, 0xe0, 0x4a, 0x60, 0xa7, 0xd0, 0x9b, 0x8b, 0xfb,
	0x24, 0xfd, 0x35, 0x59, 0x8b, 0xa1, 0x4f, 0x9a, 0x1a, 0x60, 0x43, 0x38, 0x14, 0x69, 0x4c, 0xba,
	0x80, 0x74, 0x46, 0x44, 0xbf, 0x55, 0x94, 0x17, 0x3f, 0x3d, 0xa6, 0x22, 0x1b, 0xb6, 0x46, 0xde,
	0xb8, 0xc7, 0x6b, 0x80, 0x8d, 0xa0, 0x8f, 0xc2, 0xad, 0xa8, 0xc8, 0xb7, 0x4d, 0xbe, 0x2e, 0xc4,
	0x42, 0x18, 0x68, 0xf1, 0x43, 0x96, 0x2c, 0xc4, 0xb0, 0x33, 0xf2, 0xc6, 0x3e, 0x6f, 0x60, 0x94,
	0x9b, 0x4c, 0xcb, 0xfc, 0x83, 0x94, 0xab, 0xe1, 0x21, 0x19, 0xd4, 0x00, 0x6a, 0xcb, 0x5c, 0x64,
	0x57, 0xb2, 0x4c, 0x8b, 0x61, 0x57, 0x65, 0x6e, 0x01, 0xf6, 0x0a, 0xba, 0x4b, 0x51, 0x29, 0x65,
	0x8f, 0x94, 0x56, 0x66, 0xaf, 0x01, 0x32, 0xb1, 0x8e, 0x74, 0xd1, 0x40, 0x5a, 0x07, 0x41, 0x7d,
	0xb9, 0x89, 0xa3, 0x42, 0x90, 0xbe, 0xaf, 0xf4, 0x35, 0x12, 0x7e, 0x07, 0x40, 0x6d, 0xcd, 0xa9,
	0xaf, 0xdf, 0x00, 0x64, 0x56, 0x1a, 0x7a, 0xa3, 0x60, 0xdc, 0xbf, 0xf8, 0xe4, 0x9c, 0x26, 0x70,
	0x6e, 0xbb, 0xcf, 0x1d, 0x9b, 0xf0, 0x6f, 0x0f, 0x0e, 0x6f, 0x45, 0xf5, 0xcc, 0x54, 0x54, 0xf6,
	0xaa, 0x33, 0x3e, 0x15, 0x6e, 0x65, 0xf6, 0x19, 0x74, 0x96, 0xa2, 0x7a, 0x5f, 0xae, 0xf5, 0x48,
	0xb4, 0xc4, 0x18, 0xb4, 0xa2, 0x38, 0x36, 0xc3, 0xa0, 0x6f, 0xac, 0x64, 0x5e, 0x56, 0xcd, 0x31,
	0x38, 0x08, 0x4e, 0x41, 0x4b, 0x4f, 0xb3, 0x28, 0xff, 0x9d, 0xa6, 0xd0, 0xe3, 0x0d, 0x0c, 0x33,
	0x4c, 0xd2, 0x58, 0x3c, 0xd1, 0x04, 0x02, 0xae, 0x84, 0xf0, 0x2f, 0x0f, 0x7a, 0x37, 0x93, 0xf8,
	0x72, 0x51, 0x24, 0x32, 0x65, 0x6f, 0xa1, 0x9d, 0x17, 0x51, 0x56, 0x50, 0x15, 0xfd, 0x8b, 0x17,
	0xba, 0xfc, 0x9b, 0x49, 0xfc, 0x0b, 0xc2, 0xb3, 0x03, 0xae, 0xf4, 0xec, 0x2b, 0x68, 0xc5, 0x59,
	0xf4, 0x48, 0x45, 0xf5, 0x2f, 0x4e, 0x6a, 0xbb, 0x77, 0xe5, 0x62, 0x59, 0x5d, 0x67, 0xd1, 0xe3,
	0xec, 0x80, 0x93, 0x09, 0x3b, 0x83, 0x60, 0x5e, 0x56, 0x54, 0x64, 0xdd, 0xd0, 0x9b, 0x49, 0x3c,
	0xa5, 0xe4, 0x66, 0x07, 0x1c, 0xd5, 0xec, 0x18, 0xfc, 0xa2, 0xa2, 0x9a, 0xdb, 0xdc, 0x2f, 0xaa,
	0xe9, 0x21, 0xb4, 0x1f, 0xa2, 0x55, 0x29, 0xc2, 0x11, 0x74, 0x4d, 0x78, 0x2c, 0x81, 0xbb, 0x4d,
	0x26, 0x21, 0x3c, 0x83, 0x81, 0x1b, 0x78, 0x8f, 0xd5, 0x17, 0x54, 0xa7, 0x0a, 0xba, 0xaf, 0xf7,
	0xe1, 0x5b, 0x78, 0xf1, 0x73, 0x29, 0xb2, 0x0a, 0x2d, 0x2b, 0xf2, 0xdb, 0x3d, 0xd8, 0xf0, 0x04,
	0x5e, 0x1a, 0xc3, 0x77, 0x51, 0x5e, 0xa8, 0x10, 0x09, 0x9c, 0x58, 0x30, 0xc9, 0x0b, 0xf3, 0x87,
	0xd7, 0x00, 0xd4, 0x34, 0x37, 0x29, 0x07, 0xc1, 0x08, 0x0b, 0xe2, 0xb7, 0x4f, 0xd5, 0x2b, 0x01,
	0x8f, 0x45, 0x9c, 0x64, 0x82, 0xe6, 0x42, 0x13, 0x6f, 0xf3, 0x1a, 0x08, 0x7f, 0x83, 0x53, 0x0a,
	0x35, 0x2d, 0x2b, 0x2e, 0x16, 0x32, 0x33, 0xe9, 0x5e, 0xa6, 0xf1, 0x25, 0x12, 0x66, 0x37, 0x1d,
	0x0d, 0xb5, 0x7c, 0x87, 0x5a, 0x96, 0x16, 0x81, 0x4b, 0x8b, 0x1f, 0xe0, 0x73, 0xfa, 0xff, 0xad,
	0x3e, 0x6b, 0xff, 0xf7, 0xf7, 0xe1, 0x1a, 0x8e, 0xe8, 0x47, 0xe8, 0xf6, 0xcc, 0x41, 0xd9, 0x93,
	0x99, 0xea, 0x4b, 0xb0, 0xb7, 0x2f, 0xad, 0xed, 0xbe, 0xdc, 0xd2, 0x94, 0x55, 0x4b, 0xec, 0x4f,
	0xbd, 0x5d, 0xe5, 0xfa, 0x4e, 0xb9, 0x75, 0x52, 0x81, 0x3b, 0xe4, 0x2f, 0xe1, 0xc8, 0x50, 0xef,
	0x39, 0x2e, 0x28, 0xfe, 0x21, 0xf5, 0x9e, 0xb3, 0x7a, 0x4f, 0x56, 0x76, 0x5e, 0x1f, 0x3d, 0xa1,
	0x6f, 0x61, 0xc0, 0xc5, 0x66, 0x65, 0xc8, 0xc6, 0xc6, 0xd0, 0x51, 0x57, 0xd3, 0xde, 0xab, 0x4b,
	0xeb, 0xc3, 0x0b, 0xe8, 0x1a, 0x4f, 0xf6, 0xc6, 0xcd, 0x62, 0x97, 0x93, 0xce, 0xfe, 0x7b, 0x38,
	0x26, 0x9f, 0x3a, 0xff, 0x73, 0xbc, 0x7c, 0xf1, 0x0b, 0xa3, 0xeb, 0x98, 0xc7, 0xda, 0x5d, 0x5f,
	0x8a, 0xdc, 0xb1, 0x08, 0xbf, 0xd6, 0x51, 0xf1, 0xf8, 0x8d, 0x20, 0x58, 0x8a, 0x4a, 0xc7, 0xdc,
	0x76, 0x42, 0x15, 0xb6, 0xde, 0x58, 0xab, 0xbb, 0xde, 0x92, 0x41, 0xb7, 0x8b, 0x84, 0x70, 0x06,
	0x2f, 0xc9, 0xcc, 0xb0, 0x8b, 0x3a, 0x31, 0x81, 0x41, 0xe4, 0xc8, 0x3a, 0x37, 0x73, 0x97, 0x19,
	0x53, 0xde, 0x30, 0x0a, 0xff, 0xf4, 0xa0, 0x6b, 0x39, 0xba, 0x8b, 0x38, 0xf5, 0x95, 0xe1, 0x37,
	0xae, 0xeb, 0x57, 0xd0, 0x9d, 0x97, 0xfa, 0x81, 0x52, 0x03, 0xb2, 0x72, 0x3d, 0xe3, 0xd6, 0xd6,
	0x53, 0x5d, 0xc8, 0x22, 0x5a, 0x5d, 0xc9, 0xbc, 0xa0, 0x93, 0xed, 0xf3, 0x1a, 0x40, 0x1f, 0x7a,
	0x1b, 0xf5, 0x4b, 0xaa, 0x84, 0xf0, 0x0f, 0x0f, 0x80, 0x8b, 0x85, 0x48, 0x36, 0x05, 0x8e, 0x6d,
	0x0f, 0xb3, 0x55, 0x30, 0xdf, 0x0d, 0xb6, 0x93, 0x3c, 0x58, 0x4c, 0x54, 0x9f, 0xa0, 0x80, 0x6b,
	0xa9, 0x51, 0x4c, 0x7b, 0xab, 0x98, 0xba, 0x01, 0x9d, 0xc6, 0x9d, 0xf9, 0x4f, 0x00, 0x9d, 0x2b,
	0x99, 0xde, 0x25, 0xf7, 0xb8, 0x66, 0xac, 0xa3, 0x34, 0xba, 0x17, 0x26, 0x33, 0x23, 0xd2, 0xa9,
	0x15, 0x0f, 0x62, 0x25, 0x37, 0xc2, 0x90, 0xbb, 0x06, 0x70, 0xcd, 0x78, 0x4c, 0xd2, 0x54, 0x64,
	0x53, 0xaa, 0x3c, 0xa0, 0xca, 0x5d, 0x48, 0x3f, 0xa4, 0x4a, 0xdd, 0xb2, 0x0f, 0xa9, 0xd2, 0x9d,
	0x42, 0x6f, 0x23, 0xe5, 0x4a, 0x29, 0x75, 0x3f, 0x2d, 0xc0, 0xde, 0xc0, 0xb1, 0x0d, 0x34, 0x75,
	0x1a, 0xbb, 0x85, 0x62, 0x84, 0x55, 0x72, 0xa7, 0x56, 0x05, 0xf5, 0x42, 0x5a, 0x19, 0xf3, 0x5b,
	0x22, 0x3b, 0x17, 0x19, 0xa9, 0xd5, 0x92, 0xe2, 0x42, 0x18, 0x65, 0x1d, 0x3d, 0xb9, 0x46, 0x6a,
	0x59, 0xd9, 0x42, 0xd1, 0x2e, 0x95, 0xb8, 0xdd, 0x5c, 0x0b, 0x6d, 0xa7, 0xd6, 0x96, 0x2d, 0x94,
	0x9d, 0xc1, 0x11, 0x3e, 0x9e, 0xd7, 0x62, 0x15, 0x55, 0xce, 0xf6, 0xd2, 0x04, 0xd1, 0x8a, 0xde,
	0x11, 0xbb, 0x7d, 0x0d, 0xa8, 0xb4, 0x26, 0x88, 0xcb, 0x41, 0x92, 0x2e, 0x32, 0x6b, 0x74, 0xa4,
	0x56, 0x34, 0x17, 0x9b, 0x77, 0x68, 0xe1, 0x9c, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x08, 0x02,
	0xb1, 0x97, 0x7d, 0x0a, 0x00, 0x00,
}
